services:
  db:
    image: "mysql:8.2.0"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 2
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "wex-purchases-db"
      MYSQL_USER: "lucas"
      MYSQL_PASSWORD: "miranda"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wex-purchases-db
      SPRING_DATASOURCE_USERNAME: "lucas"
      SPRING_DATASOURCE_PASSWORD: "miranda"


volumes:
  db_data: