

spring:
  profiles:
    active: "dev"
  datasource:
    url: "jdbc:mysql://localhost:3306/wex-purchases-db"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "lucas"
    password: "miranda"
  jpa:
    hibernate:
      ddl-auto: none

connections:
  external:
    connect:
      timeout_seconds: 5
    read:
      timeout_seconds: 5