server:
  servlet:
    context-path: "/wex-purchases-control"

spring:
  profiles:
    active: "prod" # dev (expose interval information stacktrace, errors details) / prod
  datasource:
    url: "jdbc:mysql://localhost:3306/${MYSQLDB_DATABASE}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "${MYSQLDB_USER}"
    password: "${MYSQLDB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: none

connections:
  external:
    connect:
      timeout_seconds: 5
    read:
      timeout_seconds: 5