server:
  servlet:
    context-path: "/wex-purchases-control"
management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  profiles:
    active: "prod" # dev (expose interval information stacktrace, errors details) / prod
  datasource:
    url: "jdbc:mysql://localhost:3306/${MYSQLDB_DATABASE}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "${MYSQLDB_USER}"
    password: "${MYSQLDB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: none

connections:
  external:
    base_url: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange"
    connect:
      timeout_seconds: 5
    read:
      timeout_seconds: 5