server:
  servlet:
    context-path: "/wex-purchases-control"

spring:
  datasource:
    url: "jdbc:mysql://localhost:${MYSQLDB_PORT}/${MYSQLDB_DATABASE}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "${MYSQLDB_USERNAME}"
    password: "${MYSQLDB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: none

connections:
  external:
    base_url: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange"
    connect:
      timeout_seconds: 5
    read:
      timeout_seconds: 5